name: Pull Request Workflow
description: Pull request workflows

inputs:
  # disallowed-packages:
  #   description: Packages to disallow
  # ghsa:
  #   description: Allow GHSA advisories
  # licenses:
  #   default: Apache-2.0,BSD-2-Clause,BSD-3-Clause,CC0-1.0,GPL-2.0,GPL-3.0,ISC,MIT
  #   description: Licenses to allow
  severity:
    default: low
    description: Severity to fail on
  timeout:
    default: "120"
    description: Timeout for each step

runs:
  using: composite
  steps:
    # Labeler
    - name: Labeler
      uses: actions/labeler@v4

    # Dependency Review
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      # TODO: options (fail, license, packages)
      with:
        # allow-ghsa: ${{ github.event.inputs.ghsa }}
        # allow-licenses: ${{ github.event.inputs.licenses }}
        # deny-packages: ${{ github.event.inputs.disallowed-packages }}
        fail-on-severity: ${{ github.event.inputs.severity }}
        retry-on-snapshot-warnings-timeout: ${{ github.event.inputs.timeout }}
        retry-on-snapshot-warnings: true
