name: Pull Request Workflow
description: Pull request workflows

inputs:
  codeql-analysis:
    description: Perform CodeQL analysis
    default: "false"
  codeql-build-script:
    description: Build script
  codeql-language:
    description: Language to analyze
  codeql-queries:
    description: Queries to run (e.g. security-extended,security-and-quality)

runs:
  using: composite
  steps:
    # Labeler
    - name: Labeler
      uses: actions/labeler@v4

    # Dependency Review
    - name: Dependency Review
      uses: actions/dependency-review-action@v3

    # CodeQL Analysis
    - name: Initialize CodeQL
      if: ${{ github.event.inputs.codeql-analysis }}
      uses: github/codeql-action/init@e4262713b504983e61c7728f5452be240d9385a7 # v2.21.5 https://github.com/github/codeql-action/commit/e4262713b504983e61c7728f5452be240d9385a7
      with:
        languages: ${{ github.event.inputs.codeql-language }}
        queries: ${{ github.event.inputs.codeql-queries }}

    - name: Autobuild
      if: ${{ github.event.inputs.codeql-analysis && ! github.event.inputs.codeql-build-script }}
      uses: github/codeql-action/autobuild@e4262713b504983e61c7728f5452be240d9385a7 # v2.21.5 https://github.com/github/codeql-action/commit/e4262713b504983e61c7728f5452be240d9385a7

    - name: Custom Build
      if: ${{ github.event.inputs.codeql-analysis && github.event.inputs.codeql-build-script }}
      shell: bash
      env:
        BUILD_SCRIPT: ${{ github.event.inputs.codeql-build-script }}
      run: |
        echo "Run, Build Application using script"
        $BUILD_SCRIPT

    - name: Perform CodeQL Analysis
      if: ${{ github.event.inputs.codeql-analysis }}
      uses: github/codeql-action/analyze@e4262713b504983e61c7728f5452be240d9385a7 # v2.21.5 https://github.com/github/codeql-action/commit/e4262713b504983e61c7728f5452be240d9385a7
      with:
        category: /language:${{ github.event.inputs.codeql-language }}
