name: Linting Workflow

inputs:
  default-branch:
    type: string
    description: Default Branch
    default: main
  helm-lint:
    type: boolean
    description: Perform Helm Linting
    default: false
  helm-version:
    type: string
    description: Helm Version
    default: v3.11.2
  validate-all:
    type: boolean
    description: Validate All Code
    default: false
  github-token:
    type: string
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Super-Linter
    - name: Lint Code Base
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: ${{ inputs.validate-all }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        GITHUB_TOKEN: ${{ inputs.token }}

    # FIXME: Helm Lint
    - name: Set up Helm
      if: ${{ inputs.helm-lint }}
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm-version }}
    - name: Lint Helm Charts
      if: ${{ inputs.helm-lint }}
      shell: bash
      run: helm lint deployment/chart
