name: Linting Workflow
description: Linting Workflow

inputs:
  default-branch:
    description: Default branch to work on
    default: main
  helm-chart:
    description: Helm chart path
  helm-lint:
    description: Perform helm linting
  helm-version:
    description: Helm version
    default: v3.12.3
  validate-all:
    description: Lint everything

runs:
  using: composite
  steps:
    # Super-Linter
    - name: Lint Code Base
      uses: github/super-linter@962a6409c1b303d0e53a9d34ada577a0362f4fae # v5.2.1 https://github.com/super-linter/super-linter/commit/962a6409c1b303d0e53a9d34ada577a0362f4fae
      env:
        DEFAULT_BRANCH: ${{ github.event.inputs.default-branch }}
        GITHUB_TOKEN: ${{ github.token }}
        VALIDATE_ALL_CODEBASE: ${{ github.event.inputs.validate-all }}

    # Helm Lint
    - name: Set up Helm
      if: ${{ github.event.inputs.helm-lint }}
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5 https://github.com/Azure/setup-helm/commit/5119fcb9089d432beecbf79bb2c7915207344b78
      with:
        version: ${{ github.event.inputs.helm-version }}

    - name: Lint Helm Charts
      if: ${{ github.event.inputs.helm-lint }}
      shell: bash
      run: helm lint deployment/chart
