name: Linting Workflow
description: Linting Workflow

inputs:
  default-branch:
    description: Default branch to work on
    default: main
  helm-chart:
    description: Helm chart path
  helm-lint:
    description: Perform helm linting
  helm-version:
    description: Helm version
    default: v3.11.2
  validate-all:
    description: Lint everything
  github-token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    # Super-Linter
    - name: Lint Code Base
      uses: github/super-linter@v5
      env:
        DEFAULT_BRANCH: ${{ github.event.inputs.default-branch }}
        GITHUB_TOKEN: ${{ github.event.inputs.token }}
        VALIDATE_ALL_CODEBASE: ${{ github.event.inputs.validate-all }}

    # Helm Lint
    - name: Set up Helm
      if: ${{ github.event.inputs.helm-lint }}
      uses: azure/setup-helm@v3
      with:
        version: ${{ github.event.inputs.helm-version }}

    - name: Lint Helm Charts
      if: ${{ github.event.inputs.helm-lint }}
      shell: bash
      run: helm lint deployment/chart
