name: Workflow Gate
description: Gate workflow based on Trivy scan results

inputs:
  upload-scan-result:
    description: Upload scan results to GitHub Security tab
  github-pat:
    description: GitHub Personal Access Token
    required: true

runs:
  using: composite
  steps:
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0 https://github.com/aquasecurity/trivy-action/commit/fbd16365eb88e12433951383f5e99bd901fc618f
      with:
        exit-code: 1
        format: sarif
        hide-progress: false
        ignore-unfixed: true
        output: trivy-results.sarif
        scan-type: fs

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@e4262713b504983e61c7728f5452be240d9385a7 # 2.21.5 https://github.com/github/codeql-action/commit/e4262713b504983e61c7728f5452be240d9385a7
      if: ${{ github.event.inputs.upload-scan-result }}
      with:
        sarif_file: trivy-results.sarif

    - name: Run Trivy SBOM and submit results to Dependency Graph
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # 0.12.0 https://github.com/aquasecurity/trivy-action/commit/fbd16365eb88e12433951383f5e99bd901fc618f
      if: ${{ inputs.generate-sbom }}
      with:
        format: github
        github-pat: ${{ github.event.inputs.github-pat }}
        image-ref: .
        output: dependency-results.sbom.json
        scan-type: fs
