name: Releases

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: labsonline/cicd/.github/workflows/release.yml@121b43dd9bbaec952cf0803972a532fde5d4adb0 # latest https://github.com/labsonline/cicd/commit/121b43dd9bbaec952cf0803972a532fde5d4adb0
    permissions:
      contents: write
