name: Releases

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: labsonline/cicd/.github/workflows/release.yml@ee4255cc0c2a62b557dd4f3a102ff8dd4e3760e5 # v0.1.0-alpha.3 https://github.com/labsonline/cicd/commit/ee4255cc0c2a62b557dd4f3a102ff8dd4e3760e5
    permissions:
      contents: write
