name: Releases

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: labsonline/cicd/.github/workflows/release.yml@d2a6707421c9ea2db7fca9118708aa2d337a6ab0 # v0.1.0 https://github.com/labsonline/cicd/commit/d2a6707421c9ea2db7fca9118708aa2d337a6ab0
    permissions:
      contents: write
