name: Contiuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # ${{ github.ref != 'refs/heads/master' }}

permissions: read-all

jobs:
  bot:
    uses: labsonline/cicd/.github/workflows/bot.yml@e18973894cf06830cfe5a432beee8eb302f724c7 # v0.1.1-alpha.1 https://github.com/labsonline/cicd/commit/e18973894cf06830cfe5a432beee8eb302f724c7
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
  gate:
    uses: labsonline/cicd/.github/workflows/gate.yml@e18973894cf06830cfe5a432beee8eb302f724c7 # v0.1.1-alpha.1 https://github.com/labsonline/cicd/commit/e18973894cf06830cfe5a432beee8eb302f724c7
  scorecard:
    uses: labsonline/cicd/.github/workflows/scorecard.yml@e18973894cf06830cfe5a432beee8eb302f724c7 # v0.1.1-alpha.1 https://github.com/labsonline/cicd/commit/e18973894cf06830cfe5a432beee8eb302f724c7
    permissions:
      id-token: write
      security-events: write
