name: Contiuos Integration

on:
  - push

permissions: read-all

jobs:
  bot:
    uses: labsonline/cicd/.github/workflows/bot.yml@latest
  gate:
    uses: labsonline/cicd/.github/workflows/gate.yml@latest
  scorecard:
    uses: labsonline/cicd/.github/workflows/scorecard.yml@latest
