name: Contiuos Integration

on:
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions: read-all

jobs:
  bot:
    uses: labsonline/cicd/.github/workflows/bot.yml@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
    permissions:
      issues: write
      pull-requests: write
      repository-projects: write
  # Uncomment if you want to use the codeql workflow
  # ast:
  #   uses: labsonline/cicd/.github/workflows/ast.yml@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
  #   with:
  #     codeql-language: ""
  gate:
    uses: labsonline/cicd/.github/workflows/gate.yml@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
  scorecard:
    uses: labsonline/cicd/.github/workflows/scorecard.yml@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
    permissions:
      id-token: write
      security-events: write
