name: Gate CI

on:
  push: {}
  pull_request: {}
  schedule:
    - cron: 30 1 * * 6

permissions: read-all

jobs:
  bot:
    uses: labsonline/cicd/.github/workflows/bot.yml@dev # FIXME: @main
  gate:
    uses: labsonline/cicd/.github/workflows/gate.yml@dev # FIXME: @main
  scorecard:
    uses: labsonline/cicd/.github/workflows/scorecard.yml@dev # FIXME: @main
  release:
    uses: labsonline/cicd/.github/workflows/release.yml@dev # FIXME: @main
  cleanup:
    uses: labsonline/cicd/.github/workflows/cleanup.yml@dev # FIXME: @main
