name: Cleanup

on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: 30 1 * * 6
  workflow_dispatch: {}

permissions: read-all

jobs:
  cleanup:
    uses: labsonline/cicd/.github/workflows/cleanup.yml@e18973894cf06830cfe5a432beee8eb302f724c7 # v0.1.1-alpha.1 https://github.com/labsonline/cicd/commit/e18973894cf06830cfe5a432beee8eb302f724c7
    permissions:
      contents: write
      issues: write
      pull-requests: write
