name: Cleanup

on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: 30 1 * * 6
  workflow_dispatch: {}

permissions: read-all

jobs:
  cleanup:
    uses: labsonline/cicd/.github/workflows/cleanup.yml@main # v0.1.0-alpha.2 https://github.com/labsonline/cicd/commit/b5ef8c3b917ae68e4dcf365b9bc645a8a486b5c3
