name: Cleanup

on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: 30 1 * * 6
  workflow_dispatch: {}

permissions: read-all

jobs:
  cleanup:
    uses: labsonline/cicd/.github/workflows/cleanup.yml@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
    permissions:
      contents: write
      issues: write
      pull-requests: write
