name: Review

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
  review:
    uses: labsonline/cicd/.github/workflows/review.yml@ee4255cc0c2a62b557dd4f3a102ff8dd4e3760e5 # v0.1.0-alpha.3 https://github.com/labsonline/cicd/commit/ee4255cc0c2a62b557dd4f3a102ff8dd4e3760e5
    permissions:
      pull-requests: write
