name: Review

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
  review:
    uses: labsonline/cicd/.github/workflows/review.yml@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
    permissions:
      pull-requests: write
