name: Cleanup Workflow

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: Branch to cleanup (e.g. refs/pull/1/merge)
        default: ${{ github.ref }}
      clean:
        type: boolean
        description: Whether to clean or not
        default: false

permissions: read-all

jobs:
  # Cleanup stale issues and PRs
  stale:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: Stale issue message
          stale-pr-message: Stale pull request message
          stale-issue-label: no-issue-activity
          stale-pr-label: no-pr-activity

  # Cleanup cache
  cache:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.clean || github.event_name == 'schedule' }}
    permissions:
      contents: write
    steps:
      - name: Cleanup cache
        shell: bash
        env:
          BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: ${{ github.action_path }}/../scripts/delete-gh-actions-cache.sh
