name: Cleanup Workflow

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: Branch to cleanup (e.g. refs/pull/1/merge)
        default: ${{ github.ref }}
      clean:
        type: boolean
        description: Whether to clean or not
        default: false

permissions:
  contents: write

jobs:
  # Cleanup stale issues and PRs
  stale:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          any-of-labels: needs-more-info,needs-demo
          days-before-close: 5
          days-before-pr-close: -1
          days-before-stale: 30
          exempt-all-pr-assignees: true
          exempt-all-pr-milestones: true
          exempt-issue-milestones: future,alpha,beta
          stale-issue-label: no-issue-activity
          stale-issue-message: Message to comment on stale issues. If none provided, will not mark issues stale
          stale-pr-label: no-pr-activity
          stale-pr-message: Message to comment on stale PRs. If none provided, will not mark PRs stale

  # Cleanup cache
  cache:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.clean || github.event_name == 'schedule' }}
    steps:
      - name: Cleanup cache
        shell: bash
        env:
          BRANCH: ${{ github.event.inputs.branch }}
          GITHUB_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: ${{ github.action_path }}/../scripts/delete-gh-actions-cache.sh
