name: Gates

on:
  - workflow_call

permissions: read-all

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Trivy Scan
        uses: labsonline/cicd/.github/actions/trivy@e18973894cf06830cfe5a432beee8eb302f724c7 # v0.1.1-alpha.1 https://github.com/labsonline/cicd/commit/e18973894cf06830cfe5a432beee8eb302f724c7
        with:
          upload-scan-result: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
