name: Gates

on:
  workflow_call:
    inputs:
      upload:
        type: boolean
        description: Upload the result to the GitHub repository
        default: false

permissions: read-all

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Trivy Scan
        uses: labsonline/cicd/.github/actions/trivy@b510ba2b18998d47dd6b725a395b9c527922370d # v0.1.0-alpha.1 https://github.com/labsonline/cicd/commit/b510ba2b18998d47dd6b725a395b9c527922370d
        with:
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          upload-scan-result: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
