name: Gates

on:
  - workflow_call

permissions: read-all

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4.0.0 https://github.com/actions/checkout/commit/3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Trivy Scan
        uses: labsonline/cicd/.github/actions/trivy@130e841e56a92a05e00e12fa55c5949de215f9b4 # v0.1.3 https://github.com/labsonline/cicd/commit/130e841e56a92a05e00e12fa55c5949de215f9b4
        with:
          upload-scan-result: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
