name: Lint

on:
  push: {}
  pull_request: {}
  workflow_call:
    inputs:
      helm:
        type: boolean
        description: Lint Helm Charts
        default: false

jobs:
  # Linting
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Helm
  helm:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.helm == true }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2
      - name: Lint Helm Charts
        run: helm lint deployment/chart
