name: Releases Workflow

on:
  workflow_call:
    inputs:
      files-path:
        type: string
        description: Path to the files to release
        default: "*"

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Pre Release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1 https://github.com/marvinpinto/action-automatic-releases/commit/919008cf3f741b179569b7a6fb4d8860689ab7f0
        with:
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ github.token }}
          title: Dev Build
          files: |
            ${{ github.event.inputs.files-path }}

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/tags/v*' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1 https://github.com/marvinpinto/action-automatic-releases/commit/919008cf3f741b179569b7a6fb4d8860689ab7f0
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          files: |
            ${{ github.event.inputs.files-path }}
