name: Releases Workflow

on:
  workflow_call:
    inputs:
      files-path:
        type: string
        description: Path to the files to release
        default: "*"

permissions:
  contents: read

jobs:
  prerelease:
    name: Prerelease
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1 https://github.com/marvinpinto/action-automatic-releases/commit/919008cf3f741b179569b7a6fb4d8860689ab7f0
        with:
          automatic_release_tag: latest
          prerelease: true
          repo_token: ${{ github.token }}
          title: Dev Build
          files: |
            ${{ github.event.inputs.files-path }}

  # FIXME: release
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # TODO: package
      # TODO: sign

      - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1 https://github.com/marvinpinto/action-automatic-releases/commit/919008cf3f741b179569b7a6fb4d8860689ab7f0
        with:
          prerelease: false
          repo_token: ${{ github.token }}
          files: |
            ${{ github.event.inputs.files-path }}
