name: Automatic Releases

on:
  workflow_call:
    inputs:
      files-path:
        type: string
        description: Path to the files to release
        default: "*"

permissions: read-all

jobs:
  releases:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.trigger == 'main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Pre Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: latest
          title: Dev Build
          files: |
            ${{ github.event.inputs.files-path }}

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ${{ github.event.inputs.files-path }}
