name: Pull Request Review

on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Assign
        uses: kentaro-m/auto-assign-action@v1.2.5
      - name: Lint
        uses: labsonline/cicd/.github/actions/lint@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Review
        uses: labsonline/cicd/.github/actions/pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
