name: Review

on:
  push: {}
  pull_request: {}
  workflow_call:
    inputs:
      codeql:
        type: boolean
        description: "Run CodeQL Analysis"
        default: false
      languages:
        type: string
        description: "Languages to run CodeQL Analysis on"
  schedule:
    - cron: 34 20 * * 6

jobs:
  # Dependency Review
  dependency:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  # CodeQL Analysis
  code:
    runs-on: ubuntu-latest
    if: ${{ inputs.codeql }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - ${{ inputs.languages }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # Trivy Scan
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          hide-progress: false
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif
      - name: Run Trivy SBOM and submit results to Dependency Graph
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          image-ref: .
          format: github
          output: dependency-results.sbom.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}
