name: Pull Request Review

on:
  - workflow_call

jobs:
  pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint
        uses: ./.github/actions/lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Review
        uses: ./.github/actions/pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
