name: Signage

on:
  - workflow_call

jobs:
  # FIXME: Sign container image
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v1.9.0
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          TAGS: ""
        run: cosign sign --recursive "${TAGS}"

  # TODO: Sign helm chart
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2
